[profile.default]
src = "src"
out = "out"
libs = ["lib"]
viaIr = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# eth-rpc-url = "https://sepolia.infura.io"
# solc = ">=0.6.2, <0.9.0"

remappings = [
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "@chainlink/contracts/=node_modules/@chainlink/contracts",
    "@chainlink/contracts-ccip/=node_modules/@chainlink/contracts-ccip",
    "@chainlink/local=node_modules/@chainlink/local"
]

[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/KX1L8OUxzzPpA2BK0oa2rRSbunp8M2aN"
# fork_block_number = 7887153

# forge test --match-test test_getLatestPrice --fork-url https://eth-sepolia.g.alchemy.com/v2/KX1L8OUxzzPpA2BK0oa2rRSbunp8M2aN --fork-block-number 7887222 -vvvv

[fmt]
line_length = 100
tab_width = 2
bracket_spacing = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

== Logs ==
  Aiki deployed at: 0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496
  AikiFactory deployed at: 0x34A1D3fff3958843C43aD80F30b94c510645C316
  AikiToken deployed at: 0x90193C961A926261B756D1E5bb255e67ff9498A1